### ISSUE TITLE
Update ReadMe with revised Installation Instructions

### ISSUE THREAD

**Issue by rjwignar** [pbelokon/BukuRain#1]
I could not install BukuRain using `npm i`.
After consulting @pbelokon I was suggested to install using `npm i -g` and can now run BukuRain:

![image](https://github.com/pbelokon/BukuRain/assets/78163326/038f79b6-dfe1-49cd-b609-518979cddbb6)

Please update the README to instruct future users to run `npm i -g` instead of `npm i` during installation.

**Comment by pbelokon** [comment]
Got it I updated the instructions, thank you for figuring it out with me
