### ISSUE TITLE
Add -c, --config flag to accept TOML file

### ISSUE THREAD

**Issue by mingming-ma** [pbelokon/BukuRain#10]
Hi, I would like to add -c, --config flags to accept a file path to a TOML-based config file. 

- If missing or improperly formatted, display an error and exit
- When -c or --config is used, other options will be ignored
- Unrecognized options in the config are ignored. 
- Missing options to default settings.
- I would update the documentation accordingly.

Let me know if I can go ahead with working on it.

Thank you.

**Comment by pbelokon** [comment]
@mingming-ma  Sure go ahead !
