### ISSUE TITLE
Suggestion: Usage Examples in ReadMe

### ISSUE THREAD

**Issue by rjwignar** [pbelokon/BukuRain#2]
It might be useful to add some usage examples for the `-i` and `-o` flags in the ReadMe, such as:
`buku -i .\examples\paragraphs.txt`
`buku -i .\examples`
`buku -o .\test -i .\examples\paragraphs.txt`

**Comment by pbelokon** [comment]
@rjwignar took a note of that and changed README could you take a look and see if it makes sense

**Comment by rjwignar** [comment]
They look great! They provide the information future users need to quickly get started with your program
